"""
WebSocket endpoint for real-time transcription and AI assistance.

Architecture (matching cheating-daddy):
- Transcription comes from frontend (Web Speech API in browser) or Electron (Gemini Live)
- Text answers are generated by Groq (primary) → Gemma fallback → Gemini fallback
- Profile-based system prompts (interview, sales, meeting, presentation, negotiation, exam)
"""
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Depends, HTTPException
from app.core.dependencies import get_current_user_ws
from app.services.groq_service import generate_text_response
from app.services.prompts import get_system_prompt
from app.config import get_settings
from app.models.user import User
from app.models.session import Session
from app.database import AsyncSessionLocal
from sqlalchemy import select
import json
import asyncio
import traceback
from datetime import datetime
from typing import Dict, Any, List
import logging

router = APIRouter()
logger = logging.getLogger(__name__)
settings = get_settings()

# Active connections
class ConnectionManager:
    def __init__(self):
        self.active_connections: Dict[str, WebSocket] = {}
        self.session_data: Dict[str, Dict[str, Any]] = {}
        self.last_processed: Dict[str, str] = {}  # Track last processed text to avoid duplicates
    
    async def connect(self, websocket: WebSocket, user_id: int, session_id: int):
        """Accept WebSocket connection"""
        await websocket.accept()
        connection_id = f"{user_id}_{session_id}"
        self.active_connections[connection_id] = websocket
        self.last_processed[connection_id] = ""
        self.session_data[connection_id] = {
            "user_id": user_id,
            "session_id": session_id,
            "transcript": [],
            "ai_responses": [],
            "questions_answered": 0,
            "current_question": "",
            "conversation_history": [],  # multi-turn context for Groq/Gemma
            "profile": "interview",
            "custom_prompt": "",
        }
        return connection_id
    
    async def disconnect(self, connection_id: str):
        """Remove connection"""
        if connection_id in self.active_connections:
            del self.active_connections[connection_id]
            
            # Cleanup
            if connection_id in self.last_processed:
                del self.last_processed[connection_id]
            
            # Save session data to database
            if connection_id in self.session_data:
                await self._save_session(connection_id)
                del self.session_data[connection_id]
    
    async def _save_session(self, connection_id: str):
        """Save session data to database"""
        try:
            data = self.session_data.get(connection_id)
            if not data:
                return
            
            async with AsyncSessionLocal() as db:
                result = await db.execute(
                    select(Session).where(Session.id == data["session_id"])
                )
                session = result.scalar_one_or_none()
                
                if session:
                    # Update session with transcript and AI responses
                    session.transcript = "\n".join([t["text"] for t in data["transcript"]])
                    session.ai_responses = data["ai_responses"]
                    session.questions_answered = data["questions_answered"]
                    session.ended_at = datetime.utcnow()
                    if session.started_at:
                        duration = (datetime.utcnow() - session.started_at).total_seconds()
                        session.duration_seconds = int(duration)
                    
                    await db.commit()
        except Exception as e:
            logger.error(f"Error saving session: {str(e)}")
    
    async def send_message(self, connection_id: str, message: dict):
        """Send message to specific connection"""
        if connection_id in self.active_connections:
            try:
                await self.active_connections[connection_id].send_json(message)
            except:
                await self.disconnect(connection_id)

manager = ConnectionManager()

@router.websocket("/ws/live-session")
async def websocket_endpoint(
    websocket: WebSocket,
    session_id: int = 0,
    token: str = ""
):
    """
    WebSocket endpoint for real-time transcription and AI assistance using Gemini 2.0 Flash
    
    Query parameters:
        - session_id: The session ID to associate with this connection
        - token: JWT token for authentication
    """
    # Authenticate user
    user = None
    try:
        user = await get_current_user_ws(token)
    except Exception as e:
        logger.warning(f"WebSocket auth failed: {e}")
        await websocket.accept()
        await websocket.send_json({"type": "error", "message": f"Authentication failed: {str(e)}"})
        await websocket.close(code=4001, reason="Unauthorized")
        return
    
    connection_id = None
    
    try:
        # Connect
        connection_id = await manager.connect(websocket, user.id, session_id)
        logger.info(f"✅ WebSocket connected: {connection_id}")
        
        # Check if Groq/Gemma/Gemini is ready
        from app.services.groq_service import groq_service, gemma_service
        
        provider_status = "groq" if groq_service.ready else ("gemma" if gemma_service.ready else "unavailable")
        
        # Send welcome message
        await manager.send_message(connection_id, {
            "type": "connected",
            "message": f"Connected! AI provider: {provider_status}. Microphone or type questions manually.",
            "session_id": session_id,
            "provider": provider_status,
            "groq_ready": groq_service.ready,
            "gemma_ready": gemma_service.ready
        })
        
        session_data = manager.session_data[connection_id]
        
        # Get session context from database
        context = {}
        try:
            async with AsyncSessionLocal() as db:
                result = await db.execute(
                    select(Session).where(Session.id == session_id)
                )
                session_obj = result.scalar_one_or_none()
                
                if session_obj:
                    context = {
                        "company_name": session_obj.company_name,
                        "role_title": session_obj.role_title
                    }
        except Exception as e:
            logger.error(f"Failed to load session context: {e}")
        
        # Listen for messages from client
        while True:
            try:
                data = await websocket.receive()
                
                if "text" in data:
                    # Text message received
                    message = json.loads(data["text"])
                    
                    if message.get("type") == "transcript":
                        # Frontend sends transcribed text (from Web Speech API)
                        transcript = message.get("text", "").strip()
                        is_final = message.get("is_final", False)
                        
                        if not transcript:
                            continue
                        
                        # Send transcript back to client (even interim ones for visual feedback)
                        await manager.send_message(connection_id, {
                            "type": "transcript",
                            "text": transcript,
                            "is_final": is_final,
                            "timestamp": datetime.utcnow().isoformat()
                        })
                        
                        # **Optimization: Only process FINAL transcripts**
                        if not is_final:
                            continue
                        
                        # **Optimization: Skip short/noise transcripts (< 10 chars)**
                        if len(transcript) < 10:
                            continue
                        
                        # **Optimization: Skip duplicates**
                        last = manager.last_processed.get(connection_id, "")
                        if transcript.lower() == last.lower():
                            continue
                        
                        manager.last_processed[connection_id] = transcript
                        
                        # Store transcript
                        session_data["transcript"].append({
                            "text": transcript,
                            "timestamp": datetime.utcnow().isoformat()
                        })
                        
                        # **Improved question detection** - more flexible matching
                        transcript_lower = transcript.lower().strip()
                        question_starters = (
                            "what", "why", "how", "when", "where", "who", "which",
                            "can you", "could you", "would you", "should", "shall",
                            "is ", "are ", "do ", "does ", "did ", "will ", "have ",
                            "tell me", "explain", "describe"
                        )
                        
                        # Check multiple signals for question detection
                        has_question_mark = "?" in transcript
                        starts_with_question = transcript_lower.startswith(question_starters)
                        # Also check if question word appears anywhere (e.g., "Hello, how are you?")
                        contains_question_word = any(f" {qw}" in f" {transcript_lower}" for qw in 
                            ["what", "why", "how", "when", "where", "who", "which", "can you", "could you"])
                        
                        is_question = has_question_mark or starts_with_question or contains_question_word
                        
                        # Only send to AI if it looks like a question
                        if is_question:
                            await manager.send_message(connection_id, {
                                "type": "thinking",
                                "message": "🤔 Generating answer..."
                            })
                            
                            try:
                                # Build system prompt from profile
                                sys_prompt = get_system_prompt(
                                    session_data.get("profile", "interview"),
                                    session_data.get("custom_prompt", ""),
                                    context,
                                )
                                
                                # Use Groq → Gemma → Gemini fallback chain
                                answer = await generate_text_response(
                                    transcript,
                                    context,
                                    system_prompt=sys_prompt,
                                    conversation_history=session_data.get("conversation_history", []),
                                )
                                
                                await manager.send_message(connection_id, {
                                    "type": "answer",
                                    "question": transcript,
                                    "answer": answer,
                                    "confidence": 0.95,
                                    "timestamp": datetime.utcnow().isoformat()
                                })
                                
                                # Track conversation history for multi-turn context
                                session_data.setdefault("conversation_history", [])
                                session_data["conversation_history"].append({"role": "user", "content": transcript})
                                session_data["conversation_history"].append({"role": "assistant", "content": answer})
                                if len(session_data["conversation_history"]) > 40:
                                    session_data["conversation_history"] = session_data["conversation_history"][-40:]
                                
                                # Store AI response
                                session_data["ai_responses"].append({
                                    "question": transcript,
                                    "answer": answer,
                                    "timestamp": datetime.utcnow().isoformat()
                                })
                                session_data["questions_answered"] += 1
                            
                            except Exception as e:
                                logger.error(f"AI processing error: {str(e)}")
                                await manager.send_message(connection_id, {
                                    "type": "error",
                                    "message": f"Error: {str(e)}"
                                })
                    
                    elif message.get("type") == "manual_question":
                        # Manual question input
                        question = message.get("question", "").strip()
                        if question:
                            await manager.send_message(connection_id, {
                                "type": "thinking",
                                "message": "🤔 Generating answer..."
                            })
                            
                            try:
                                sys_prompt = get_system_prompt(
                                    session_data.get("profile", "interview"),
                                    session_data.get("custom_prompt", ""),
                                    context,
                                )
                                
                                answer = await generate_text_response(
                                    question,
                                    context,
                                    system_prompt=sys_prompt,
                                    conversation_history=session_data.get("conversation_history", []),
                                )
                                
                                await manager.send_message(connection_id, {
                                    "type": "answer",
                                    "question": question,
                                    "answer": answer,
                                    "confidence": 0.9,
                                    "timestamp": datetime.utcnow().isoformat()
                                })
                                
                                # Track conversation
                                session_data.setdefault("conversation_history", [])
                                session_data["conversation_history"].append({"role": "user", "content": question})
                                session_data["conversation_history"].append({"role": "assistant", "content": answer})
                                
                                session_data["questions_answered"] += 1
                                session_data["transcript"].append({
                                    "text": f"Q: {question}",
                                    "timestamp": datetime.utcnow().isoformat()
                                })
                                session_data["ai_responses"].append({
                                    "question": question,
                                    "answer": answer,
                                    "timestamp": datetime.utcnow().isoformat()
                                })
                            except Exception as e:
                                await manager.send_message(connection_id, {
                                    "type": "error",
                                    "message": f"Failed to generate answer: {str(e)}"
                                })
                    
                    elif message.get("type") == "set_profile":
                        # Change active profile mid-session
                        new_profile = message.get("profile", "interview")
                        custom_prompt = message.get("custom_prompt", "")
                        session_data["profile"] = new_profile
                        session_data["custom_prompt"] = custom_prompt
                        await manager.send_message(connection_id, {
                            "type": "profile_updated",
                            "profile": new_profile,
                            "timestamp": datetime.utcnow().isoformat()
                        })
                    
                    elif message.get("type") == "ping":
                        # Keep-alive ping
                        await manager.send_message(connection_id, {
                            "type": "pong",
                            "timestamp": datetime.utcnow().isoformat()
                        })
                
            except WebSocketDisconnect:
                break
            except Exception as e:
                logger.error(f"Error processing message: {str(e)}")
                break
    
    except Exception as e:
        logger.error(f"WebSocket error: {str(e)}")
    
    finally:
        # Cleanup
        if connection_id:
            await manager.disconnect(connection_id)
            logger.info(f"WebSocket disconnected: {connection_id}")
